# 5 PyTorch functions for Indexing, Slicing, Joining, Mutating Ops

The torch package contains data structures for multi-dimensional tensors and mathematical operations over these are defined. Additionally, it provides many utilities for efficient serializing of Tensors and arbitrary types, and other useful utilities. 

- chunk
- dstack
- hstack
- index_select
- masked_select

Before we begin, let's install and import PyTorch


In [2]:
# Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy torch torchvision torchaudio

In [3]:
# Import torch and other required modules
import torch

## Function 1 - chunk

---



This split a tensor in a specif number of chunks, Each chunk is a view of input tensor.

In [4]:
# Example 1 - working (change this)
t1 = torch.tensor([[1, 2], [3, 4.],[5,6]])


torch.chunk(t1,3,0)

(tensor([[1., 2.]]), tensor([[3., 4.]]), tensor([[5., 6.]]))

In above example the tensor is spliited into 3 chunks as specified by integer 3 

In [5]:
# Example 2 - working
t2 = torch.tensor([[4, 2], [3, 7.],[8,6],[3,7]])
t2

tensor([[4., 2.],
        [3., 7.],
        [8., 6.],
        [3., 7.]])

In [6]:
torch.chunk(t2,3,1)

(tensor([[4.],
         [3.],
         [8.],
         [3.]]), tensor([[2.],
         [7.],
         [6.],
         [7.]]))

In the above example the tensor is splitted along different axis for chunking the tensor.


In [7]:
# Example 3 - breaking (to illustrate when it breaks)
t3 = torch.tensor([[4, 2], [3, 7.],[8,6],[3,7]])
t3


tensor([[4., 2.],
        [3., 7.],
        [8., 6.],
        [3., 7.]])

In [8]:
torch.chunk(t3,3,2)

IndexError: ignored

The above error comes "Index Error" as the dim given to split that dim is not available , therefore the above error occured

This function can be used when we need to split a tensor which have inputs and targets for machine learning in same tensor 

Let's save our work using Jovian before continuing.

In [ ]:
!pip install jovian --upgrade --quiet

In [ ]:
import jovian

In [9]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Please enter your API key ( from https://jovian.ai/ ):
API KEY: ··········
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/raghavsodhi02/01-tensor-operations


'https://jovian.ai/raghavsodhi02/01-tensor-operations'

## Function 2 - dstack

This stack the tensors depthwise along the third axis. This is equivalent to concatenation along the third axis after 1-D and 2-D tensors have been reshaped.

In [10]:
 t4 = torch.tensor([1, 2, 3])
t5 = torch.tensor([4, 5, 6])
torch.dstack((t4,t5))

tensor([[[1, 4],
         [2, 5],
         [3, 6]]])

As can be seen in above example a 1 D array is stacked above other in 3-D array and also reshaped simulaneously

In [11]:
t6 = torch.tensor([[4,6,12],[23,21,31]])
t7 = torch.tensor([[23,12,45],[21,34,56]])
torch.dstack((t6,t7))

tensor([[[ 4, 23],
         [ 6, 12],
         [12, 45]],

        [[23, 21],
         [21, 34],
         [31, 56]]])

In the above example it can be seen that d stack is used to reshape a 2-D array and also it is evident from above example that it uses to reshape the arrays in 3-D only each time.

In [12]:
t8 = torch.tensor([24,56,21])
torch.dstack(t8)

TypeError: ignored

As can be seen the dstack function takes tuple of tensors and cannot reshape only a single tensor

This function can be used to reshape 1-D and 2-D arrays into 3-D , when it is required to concatenate two arrays and also reshape the same 

In [13]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/raghavsodhi02/01-tensor-operations


'https://jovian.ai/raghavsodhi02/01-tensor-operations'

## Function 3 - hstack

Stack tensors in sequence horizontally (column wise).

This is equivalent to concatenation along the first axis for 1-D tensors, and along the second axis for all other tensors. 

In [14]:
t9 = torch.tensor([76,34,21])
t10 = torch.tensor([21,43,65])
torch.hstack((t9,t10))

tensor([76, 34, 21, 21, 43, 65])

AS can be seen this concatenate the 1-D tensors horizontally one after other 

In [15]:
t11 = torch.tensor([[1],[2],[3]])
t12  = torch.tensor([[4],[5],[6]])
torch.hstack((t11,t12))


tensor([[1, 4],
        [2, 5],
        [3, 6]])

In the above examplee a 2-D array is stacked along the second axis 

In [16]:
t13 = torch.tensor([2,54,21])
torch.hstack(t13)

TypeError: ignored

This function as it is a joining function will take 2 input tensors as tuples and not a single tensor

This is use to horizontally concatenate tensors 

In [17]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/raghavsodhi02/01-tensor-operations


'https://jovian.ai/raghavsodhi02/01-tensor-operations'

## Function 4 - index_select
Returns a new tensor which indexes the input tensor along dimension dim using the entries in index which is a LongTensor.

The returned tensor has the same number of dimensions as the original tensor (input). The dimth dimension has the same size as the length of index; other dimensions have the same size as in the original tensor.

In [18]:
t14 = torch.randn(3,5)
print(t14)
indices = torch.tensor([0,2])
torch.index_select(t14,0,indices)

tensor([[ 0.2762, -0.8470,  1.5077, -1.3800, -0.7251],
        [ 0.6594, -0.9567,  0.0092, -0.3886, -0.7738],
        [ 1.5880, -1.1027, -0.1014,  0.2589, -0.5257]])


tensor([[ 0.2762, -0.8470,  1.5077, -1.3800, -0.7251],
        [ 1.5880, -1.1027, -0.1014,  0.2589, -0.5257]])

As can be seen in the above example tensor is index and selected along the tensor given in indices and horizontal row dimension as specified by dim = 0

In [19]:
torch.index_select(t14,1,indices)

tensor([[ 0.2762,  1.5077],
        [ 0.6594,  0.0092],
        [ 1.5880, -0.1014]])

As can be seen in the above example tensor is index and selected along the tensor given in indices and columns dimension 
as specified by  dim = 1

In [20]:
torch.index_select(t14,2,indices)

IndexError: ignored

The error is caused due to giving the index dimension out of range which should be max till 1 but given as 2 in above case 

This function can be used to easily indx out tensor out of given tensors at any position which is predefined Closing comments about when to use this function

In [21]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/raghavsodhi02/01-tensor-operations


'https://jovian.ai/raghavsodhi02/01-tensor-operations'

## Function 5 - masked_select
Returns a new 1-D tensor which indexes the input tensor according to the boolean mask mask which is a BoolTensor.

The shapes of the mask tensor and the input tensor don’t need to match, but they must be broadcastable.

Add some explanations

In [22]:
t15 = torch.randn(3,4)
print(t15)
mask = t15.ge(0.5)
print(mask)
torch.masked_select(t15,mask)

tensor([[ 1.4976,  1.5047, -0.3992, -0.9102],
        [ 0.7531, -0.4691,  0.3970, -0.5437],
        [ 1.2477,  0.6512,  0.6134,  1.0374]])
tensor([[ True,  True, False, False],
        [ True, False, False, False],
        [ True,  True,  True,  True]])


tensor([1.4976, 1.5047, 0.7531, 1.2477, 0.6512, 0.6134, 1.0374])

As can be seen in above example the tensor is selected along the boolean mask of true and false given in mask function

In [23]:
mask2 = torch.tensor([True, False, False,True])
torch.masked_select(t15,mask2)

tensor([ 1.4976, -0.9102,  0.7531, -0.5437,  1.2477,  1.0374])

If the given boolean tensor is not same shape as given tensor but still broadcastable , this function works fine

In [24]:
mask3 = torch.tensor([True, False])
torch.masked_select(t15,mask3)

RuntimeError: ignored

As in above case the masked tensor is also not broadcastable to the given tensor , hece the RuntimeError occured for the same.

This can be  used to select values from a given tensor according to the boolean tensor given.

In [25]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/raghavsodhi02/01-tensor-operations


'https://jovian.ai/raghavsodhi02/01-tensor-operations'

## Conclusion

The functions covered in above notebooks can be used to modify given tensors 

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* ...

In [26]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/raghavsodhi02/01-tensor-operations


'https://jovian.ai/raghavsodhi02/01-tensor-operations'